name: default
channels:
  - conda-forge
  - nodefaults
dependencies:
  - coiled >=1.89.0,<2
  - distributed >=2025.2.0,<2026
  - fsspec >=2025.3.0,<2026
  - geopandas >=1.0.1,<2
  - icechunk >=0.2.8,<0.3
  - netcdf4 >=1.7.2,<2
  - opencv >=4.10.0,<5
  - pooch >=1.8.2,<2
  - pydantic >=2.10.6,<3
  - rioxarray >=0.18.2,<0.19
  - s3fs >=2025.3.0,<2026
  - windrose >=1.9.2,<2
  - xarray >=2025.3.0,<2026
  - zarr >=3.0.5,<4
  - python >=3.12
  - pip
  - pip:
      - -e .
