branch: QA
storage_root: /tmp/ocr
wipe: true
vector:
  branch: QA
  storage_root: /tmp/ocr
  prefix: intermediate/fire-risk/vector/QA/
  wipe: true
icechunk:
  branch: QA
  storage_root: /tmp/ocr
  prefix: intermediate/fire-risk/tensor/QA/template.icechunk
  wipe: true
chunking:
  chunks:
    longitude: 6000
    latitude: 4500
