name: end-to-end

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # Daily “At 00:00”

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

env:
  COLUMNS: 120 # Set the terminal width to 120 columns for rich
jobs:
  test:
    runs-on: ubuntu-latest
    if: |
      github.event_name != 'pull_request' ||
      (
        (
          contains(github.event.pull_request.labels.*.name, 'e2e')
        ) ||
        (
          contains(github.event.pull_request.title, '[e2e]') ||
          contains(github.event.pull_request.body, '[e2e]')
        )
      )
    steps:
      - uses: actions/checkout@v5

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::631969445205:role/github-action-role
          role-session-name: ocr-etl-role-session
          aws-region: us-west-2

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.43.3
          cache: false # no pixi.lock
          locked: false
          environments: deploy

      - name: List installed libraries/packages
        run: |
          pixi install --environment deploy
          pixi list --environment deploy

      - name: process-region
        run: |
          pixi run --environment deploy ocr process-region y2_x4 --platform local --env-file ocr-local.env --init-repo
      - name: aggregate geoparquet regions
        run: |
          pixi run --environment deploy ocr aggregate --platform local --env-file ocr-local.env
      - name: write regional analysis files
        run: |
          pixi run --environment deploy ocr write-aggregated-region-analysis-files --platform local --env-file ocr-local.env
      - name: aggregate region risk summary stats
        run: |
          pixi run --environment deploy ocr aggregate-region-risk-summary-stats --platform local --env-file ocr-local.env
      - name: create regional pmtiles
        run: |
          pixi run --environment deploy ocr create-regional-pmtiles --platform local --env-file ocr-local.env

      - name: create pmtiles
        run: |
          pixi run --environment deploy ocr create-pmtiles --platform local --env-file ocr-local.env
