name: Build and push ocr image

on:
  push:
    branches:
      - main
    # paths:
    #   - ".github/workflows/ocr-image.yaml"
    #   - ".binder/**"
  pull_request:
    branches:
      - main
    # paths:
    #   - ".github/workflows/ocr-image.yaml"
    #   - ".binder/**"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: prefix-dev/setup-pixi@v0.9.0
        with:
          pixi-version: v0.43.3
          cache: false # no pixi.lock
          locked: false
          environments: deploy
          activate-environment: true

      - name: Set Environment Variables
        run: |
          echo "DATE_TAG=$(TZ='America/Seattle' date +'%Y.%m.%d')" >> "$GITHUB_ENV"

      - name: Export pixi environment to .binder/environment.yaml
        run: |
          pixi project export conda-environment --environment deploy > .binder/environment.yaml
          ls -la .binder
          cat .binder/environment.yaml

      # For biggish images, github actions runs out of disk space.
      # So we cleanup some unwanted things in the disk image, and reclaim that space for our docker use
      # https://github.com/actions/virtual-environments/issues/2606#issuecomment-772683150
      # and https://github.com/easimon/maximize-build-space/blob/b4d02c14493a9653fe7af06cc89ca5298071c66e/action.yml#L104
      # This gives us a total of about 52G of free space, which should be enough for now
      - name: cleanup disk space
        run: |
          sudo rm -rf /usr/local/lib/android /usr/share/dotnet /opt/ghc
          df -h

      - name: Build and push the image to quay.io ${{ matrix.environment }}
        uses: jupyterhub/repo2docker-action@master
        with:
          # Make sure username & password/token pair matches your registry credentials
          DOCKER_USERNAME: ${{ secrets.QUAY_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
          DOCKER_REGISTRY: "quay.io"
          ADDITIONAL_TAG: ${{ env.DATE_TAG }}
          # Disable pushing a 'latest' tag, as this often just causes confusion
          # LATEST_TAG_OFF: true
          IMAGE_NAME: "carbonplan/ocr"
